export module Player;

import <iostream>;
import <memory>;
import <map>;
import <vector>;
import <string>;
import Constants;
import Observer;
import Board;
import Link;
import Ability;
import LinkBoost;
import Firewall;
import Download;
import Scan;
import Polarize;
import Upgrade; 
import Theft;
import Obstacle;
import HTVirus;
import xwindow;

export class Player : public Observer {
	int downloaded_virus_amount;
    int downloaded_data_amount;
	int ability_amount;
	bool lose;
	bool win;
	bool graphic;
	Board *board;
	std::vector<std::unique_ptr<Ability>> abilities;
	std::vector<Link *> owned_links;
	std::vector<Link *> downloaded_links;
	Xwindow window;
	public:
		Player(std::string name, Board *board, std::string abilitychosen = DEFAULT_ABILITY_ORDER, bool graphic = true);
		int getDownloadedVirusAmount();
		int getDownloadedDataAmount();
		int getAbilityAmount();
		Ability * getAbility(int ability_id);
		bool movable();
		int getUsableAbilityAmount();
		bool isWin();
		bool isLose();
		void download(char link_char) override;
		void addLink(char link_char) override;
		void addAbility(char ability_char) override;
		char removeAbility() override;
		void usingAbility(int ability_id, std::string command);
		void movingLink(std::string command);
		void displayAbility(std::ostream &os);
		void printPlayerView(std::ostream &os);
		void printPlayer(std::ostream &os, bool hidden);
};
